openapi: 3.0.1
info:
  title: countries
  description: API Definition of countries
  version: 1.0.0
servers:
- url: http://localhost:8290/countries
paths:
  /data:
    get:
      responses:
        default:
          description: Default response
